### ISSUE TITLE
Not working on 1.16.5.

### ISSUE THREAD

**Issue by andriiqx** [KosmX/emotes-replaymod-compat#2]
I've tried everything. My setup: last fabric 1.16.5, last fabric-api 1.16.5, last version of emotecraft 1.16.5, last version of kotlin support, and nothing. Can you help me?

**Comment by KosmX** [comment]
Please share game logs/crash report.

**Comment by andriiqx** [comment]
> Please share game logs/crash report.

Description: Initializing game
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'emotes-compat-rp'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.FabricLoaderImpl$$Lambda$2379/851934733.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: LOCAL_EMOTE_STOP
	at dev.kosmx.emotesCompat.rp.ClientInitKt.initializeClient(ClientInit.kt:16)
	at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:187)
	at com.sun.proxy.$Proxy27.onInitializeClient(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.Hooks$$Lambda$2375/302371874.accept(Unknown Source)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.FabricLoaderImpl$$Lambda$2379/851934733.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1372705280 bytes (1309 MB) / 1758461952 bytes (1677 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 8
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		bendy-lib: Bendy api 1.2.2
		emotecraft: Emotecraft 2.2.5
		emotes-compat-rp: Emotecraft compatibility layer 1.0.2
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-language-kotlin: Fabric Language Kotlin 1.9.4+kotlin.1.8.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.15.6
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5
		mixinextras: MixinExtras 0.3.2
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.21
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		player-animator: Player Animator 0.3.5+1.16.5
		replaymod: Replay Mod 1.16.4-2.6.13
	Launched Version: fabric-loader-0.15.6-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```
