### ISSUE TITLE
Not working 1.20.4

### ISSUE THREAD

**Issue by ZatoUyutnOUmirat** [KosmX/emotes-replaymod-compat#3]
I tried changing the version to 1.20 and 1.20.1 but it didn't work . Can u help me?
[22:29:25] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.10
[22:29:25] [main/WARN]: Mod resolution failed
[22:29:25] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE emotes-compat-rp 1.0.2 {depends fabric-language-kotlin @ [>=1.9.0+kotlin.1.8.0]}, ROOT_FORCELOAD_SINGLE emotes-compat-rp 1.0.2]
[22:29:25] [main/INFO]: Reason: [HARD_DEP emotes-compat-rp 1.0.2 {depends fabric-language-kotlin @ [>=1.9.0+kotlin.1.8.0]}]
[22:29:25] [main/INFO]: Fix: add [add:fabric-language-kotlin 1.9.0+kotlin.1.8.0 ([[1.9.0+kotlin.1.8.0,в€ћ)])], remove [], replace []
[22:29:25] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric-language-kotlin, version 1.9.0+kotlin.1.8.0 or later.
More details:
	 - Mod 'Emotecraft compatibility layer' (emotes-compat-rp) 1.0.2 requires version 1.9.0+kotlin.1.8.0 or later of fabric-language-kotlin, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?]

**Comment by ZatoUyutnOUmirat** [comment]
Fabric Language Kotlin not helped me , mod still not working , but with this mod , i started minecraft

**Comment by ZatoUyutnOUmirat** [comment]
Fabric Language Kotlin helped me
